site_name: HandBrake MCP Server
site_description: Professional video transcoding server using HandBrakeCLI with MCP integration
site_author: Sandra Schi
site_url: https://sandraschi.github.io/handbrake-mcp/

repo_name: sandraschi/handbrake-mcp
repo_url: https://github.com/sandraschi/handbrake-mcp
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Sandra Schi

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  logo: assets/logo.png

plugins:
  - search
  - macros:
      include_dir: docs/includes
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: sandraschi/handbrake-mcp
      branch: main
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: sandraschi
      repo: handbrake-mcp
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quick-start.md
      - Configuration: configuration.md
  - User Guide:
      - Basic Usage: usage/basic.md
      - Advanced Features: usage/advanced.md
      - Batch Processing: usage/batch.md
      - Watch Folders: usage/watch.md
  - API Reference:
      - MCP Tools: api/tools.md
      - Configuration: api/config.md
      - Examples: api/examples.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Building: development/building.md
  - About:
      - Changelog: about/changelog.md
      - Roadmap: about/roadmap.md
      - FAQ: about/faq.md

extra:
  version:
    provider: mike
    default: latest

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sandraschi/handbrake-mcp
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/sandraschi/handbrake-mcp
    - icon: fontawesome/solid/globe
      link: https://sandraschi.github.io/handbrake-mcp/

  generator: false

# Extensions
hooks:
  - docs/hooks.py

# Additional CSS and JS
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

# Google Analytics
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

